### ISSUE TITLE
xcode Cannot complete automatically

### ISSUE THREAD

**Issue by andi911** [devxoul/Then#73] opened 2019-07-11 03:10 UTC
![image](https://user-images.githubusercontent.com/8968514/61019340-6bdfdd80-a3cc-11e9-8f66-7cb4b03efd1a.png)

**Comment by devxoul** [comment] 2019-09-07 13:04
Duplicate of #71. It is fixed in Xcode 11.

**Closed as completed by devxoul** 2019-09-07 13:04 UTC
Labels: duplicate
